config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  root 'posts#index'
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_as_read
  get 'notifications/:id/mark_as_unread', to: 'notifications#mark_as_unread', as: :mark_as_unread

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :comment_id, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end

  def index
    @notifications = current_user.notifications.includes(:notified_by).order('created_at DESC')
  end

  def mark_as_read
    @notification = Notification.find(params[:id])
    @notification.update read: true
    respond_to do |format|
      format.js {render 'notifications/mark_notification'}
    end
  end

  def mark_as_unread
    @notification = Notification.find(params[:id])
    @notification.update read: false
    respond_to do |format|
      format.js {render 'notifications/mark_notification'}
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def marked_notification(notification)
    if notification.read
      return link_to '', mark_as_unread_path(notification.id), remote: true,
              title: 'Mark as unread',
              class: "glyphicon glyphicon-flag mark-as-read"

    else
      return link_to '', mark_as_read_path(notification.id), remote: true,
              title: 'Mark as read',
              class: "glyphicon glyphicon-ok mark-as-read"
    end
  end

  def set_notification_title(notification)
    return 'Mark as unread' if notification.read

  end

  def count_notifications
    current_user.notifications.where(read: false).count
  end
end

app/views/notifications/_counter.html.haml
= count_notifications
%span.glyphicon.glyphicon-flag

app/views/notifications/_notification.html.haml
%li.single-notification{class: "#{dom_id(notification)}"}
  = link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post", link_through_path(notification)
  .time-ago
    = time_ago_in_words notification.created_at
    = " ago"
    = marked_notification notification

app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button.btn.btn-default.dropdown-toggle{ type: 'button', id: 'dropdownMenu1', data: { toggle: 'dropdown' }, 'aria-haspopup': true, 'aria-expanded': true }
    = render 'notifications/counter'
  = render 'notifications/unread'

app/views/notifications/_unread.html.haml
%ul.dropdown-menu{ 'aria-labelledby': 'dropdownMenu1' }
  %li.dropdown-header.text-center Notifications
  = render current_user.notifications.where(read: false).includes(:notified_by).order('created_at DESC').last(5)
  %li.divider{ role: 'separator' }
    %li.text-center= link_to 'View All', notifications_path

app/views/notifications/index.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %ul.notification-index-list
        = render @notifications

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>

app/views/notifications/mark_notification.js.erb
$(".<%= dom_id @notification %>").replaceWith("<%= j (render @notification) %>");
$(".notification-dropdown").replaceWith("<%= j (render 'notifications/notification_dropdown') %>");